# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNFillConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CommaSeparatedIntegerField(max_length=20, unique=True)),
                ('ch_type', models.IntegerField(choices=[(0, 'Manifold'), (1, 'Vent'), (2, 'Detector')], default=2)),
                ('ch_name', models.CharField(max_length=30)),
                ('ch_enable', models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable')], default=0)),
                ('ch_addresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lnmain.Ch_Addresses')),
            ],
        ),
        migrations.RemoveField(
            model_name='lnfillcong',
            name='ch_addresses',
        ),
        migrations.DeleteModel(
            name='LNFillCong',
        ),
    ]
