# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnmain', '0002_auto_20160317_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnfillconf',
            name='ch_addresses',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lnmain.Ch_Addresses'),
        ),
        migrations.AlterField(
            model_name='lnfillconf',
            name='ch_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
