# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnmain', '0003_auto_20160317_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnfillconf',
            name='ch_addresses',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='lnmain.Ch_Addresses'),
        ),
    ]
